version: "3.9"
services:

  db:
    image: postgres:15.2
    command: postgres -c 'max_connections=410'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha_prod
    #ports:
      #- 24041:5432
    volumes:
      - rinha_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "--username=postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.8'
          memory: '150MB'

  api1:
    image: rinha_2024:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.275'
          memory: '150MB'
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/rinha_prod
      ERL_MAX_PORTS: 2048
      HTTP_SERVER_PORT: 4000
      DB_CONNS: 200
    ports:
      - 4000:4000
    depends_on:
     - db

  api2:
    image: rinha_2024:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.275'
          memory: '150MB'
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/rinha_prod
      ERL_MAX_PORTS: 2048
      HTTP_SERVER_PORT: 4001
      DB_CONNS: 200
    ports:
      - 4001:4001
    depends_on:
     - api1

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '100MB'

volumes:
  rinha_volume: